- alias: Renew Guest Password
  description: Every Thursday at 8:55pm
  triggers:
  - trigger: time_pattern
    hours: '20'
    minutes: '55'
    seconds: '00'
  conditions:
  - condition: time
    weekday:
    - thu
  actions:
  - action: button.press
    metadata: {}
    data: {}
    target:
      entity_id: button.epaper_display_driver_rotate_guest_password
  mode: single
